### ISSUE TITLE
signing error

### ISSUE THREAD

**Issue by erikdung** [l-ra/openeet-shell#1]
Hello,
I have tried signing process with xmlsec1 but I got different signatureValue than in sample on etrzby.cz. Any idea where is the problem? Thanks

**Comment by l-ra** [comment]
Hi, 
if you look at the SOAP message I have to do some minor tweaks because xmlsec1 does not support WS-Security. The signature reference in the original examples uses ID syntax targeting attribute from WS-Security spec/schema. But xmlsec1 does not recognize the attribute as an ID attribute. That is why I had to change the XML a bit and add xml:id attribute. This change probably modifies the canonical form of the signed data and as a result the signatureValue is also different.
Or ... there can be any other issue :-)

**Comment by erikdung** [comment]
How do generate the private.key from this .p12 file?

**Comment by l-ra** [comment]
The privat key is stored in the p12 file. No need to  generate it. Just use it.

**Comment by l-ra** [comment]
Sorry for missunderstanding you question - now looking back i understand better. You need to convert p12 file to private.key. I added example script in the repo in commit https://github.com/l-ra/openeet-shell/commit/b3c6fcc49382bc71047a57b0b1109313a2507d7c. See https://github.com/l-ra/openeet-shell/blob/master/p12-to-cert-and-key.sh
